// <auto-generated />
namespace SocialStorytelling.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Recordwhohasvotedonastory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Recordwhohasvotedonastory));
        
        string IMigrationMetadata.Id
        {
            get { return "201403280404312_Record who has voted on a story"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
