// <auto-generated />
namespace SocialStorytelling.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddStoryClosed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStoryClosed));
        
        string IMigrationMetadata.Id
        {
            get { return "201404071608135_AddStoryClosed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
